### ISSUE TITLE
Shouldn't view-related data be modeled in the ViewModel?

### ISSUE THREAD

**Issue by oliviadodge** [android/sunflower#702]
I noticed in the PlantListFragment that there is a `setHasOptionsMenu(true)` call when the Fragment is created. Shouldn't this view-related boolean be modeled in the corresponding ViewModel? I made a PR to show what I mean: #703

**Comment by oliviadodge** [comment]
Also, I know my solution isn't perfect in that the "hasOptionsMenu" parameter is set up as a *Mutable*LiveData object, when in reality it is just a constant, but I did this to keep the variables exposed consistent, i.e. all of them as LiveData objects. Shouldn't the view remain ignorant of whether the data in the ViewModel is retrieved asynchronously or it is just a constant?

**Comment by forsenonlhaimaisentito** [comment]
I don't think it should be in the ViewModel as the options menu is a presentation detail, and not the data to be presented.

Whether to provide an options menu or not, or even which options to display, are presentation details and shouldn't be the ViewModel's responsibility, otherwise there would be tight coupling between it and the UI controller (e.g. the related Fragment).

**Comment by oliviadodge** [comment]
Yeah, that's true. I guess you don't need to model static stuff in the ViewModel since then you'd wonder where to draw the line. 

But what if showing the options menu was based on the data? Like if it gets hidden when the plants loaded don't have associated grow zone numbers. Would you want to model it then?

Just trying to figure out what all should be modeled by the ViewModel and why. I suppose only things that are dynamic.

**Comment by arriolac** [comment]
Thanks for raising this - this is no longer an issue since Sunflower was migrated to Compose
