### ISSUE TITLE
Why logic is written inside onCreateView() instead of onViewCreated() method?

### ISSUE THREAD

**Issue by PoojaDorwal** [android/sunflower#737]
_The docs for Fragment.onCreateView() now says:_

**It is recommended to only inflate the layout in this method and move logic that operates on the returned View to onViewCreated(View, Bundle).**

In all the fragments the logic is written inside the onCreateView() method but as per the official documents the logic should be written inside the onViewCreated() method.

**Comment by devsparkles** [comment]
Good question.

**Comment by RoarGronmo** [comment]
What about Activity's OnCreate... there aren't any onViewCreated, should we use onActivityCreated?

**Comment by rodrigoliveirac** [comment]
> What about Activity's OnCreate... there aren't any onViewCreated, should we use onActivityCreated?

You should not write logic inside Activities in order to avoid memory leak in your application and some crashes as well(because the Activity operates on  the MainThread) which it's could cause uncomfortable user experiences. However, you could use this method such as retrieving views or restoring state.

**Comment by arriolac** [comment]
This is no longer an issue since Sunflower was migrated to Compose. Generally, yes, inflation should be done in `onCreateView` and logic that should be done post-inflation should be done in `onViewCreated`.
