### ISSUE TITLE
Show image under status bar in plant details screen

### ISSUE THREAD

**Issue by qamarelsafadi** [android/sunflower#869]
As an improvement for Layout, we can make the status bar transparent on the Details screen as the status bar can be part of the layout, 

### What is currently showing is  👇🏻 : 

<img width="407" alt="Screenshot 2023-06-28 at 4 59 39 PM" src="https://github.com/android/sunflower/assets/30949634/7693e5f4-7ad9-420a-a6fa-b23853bdc447">

### What I am suggesting is 👇🏻 : 

<img width="440" alt="Screenshot 2023-06-28 at 5 01 41 PM" src="https://github.com/android/sunflower/assets/30949634/c56e77c7-26b7-4768-95de-a3a800cf576a">

## 

Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

**Comment by qamarelsafadi** [comment]
Done, 

Please let me know if we can reopen the issue.

**Comment by arriolac** [comment]
Ah, yes this should be done. Note that the status bar is already transparent (https://github.com/android/sunflower/blob/49520f7113a48012211a59ffb33087711c1bd313/app/src/main/res/values/styles.xml#L38) - it's the insets that need to be adjusted so that the image. I'd prefer if this change can be done against the `m3` branch since there are other status bar/inset related issues in `main` that will be addressed once `m3` is merged in.
